### ISSUE TITLE
수정해보실래요?

### ISSUE THREAD

**Issue by crongro** [developersoom/cs-level1#1]
몇 가지 안내해드릴테니 수정해보실래요? 

- var arr = [1, 2, 3, 4, 5, 6, 7, 8, 9];  를 없애고 랜덤값을 생성해보세요.
- var 대신에 let이나 const를 사용해보세요.
- 이 코드를 조금  줄여서 표현해보세요. (가로줄을 줄이던, 다른방법을 사용하던)
              while ((isNaN(inputNum) || typeof inputNum !== 'number' || inputNum > 1000 || inputNum < 100 || (inputNum + '').indexOf('0') > -1)) {

**Comment by developersoom** [comment]
안내해주신 사항 수정했습니다. 가능하다면 한번 더 검토 부탁드려도 될까요? 고맙습니다.

**Comment by crongro** [comment]
수정 잘 하셨어요.
프로그래밍으로 문제를 푸는 게 정답이 있는건 아닙니다.
여러가지 방법으로 문제를 풀 수 있고, 좋은 시도를 하신거 같네요.
수정하느라 수고하셨어요. 
:-)

**Comment by developersoom** [comment]
감사합니다!! :)
